{% set name = "harlequin-databricks" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin_databricks-{{ version }}.tar.gz
  sha256: 330adf1b74bb6ed9a31659a816fe158f69405783fcd00fba9e31261d0f8cd503

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build
    - pip
  run:
    - python >={{ python_min }}
    - harlequin >=2.0.4
    - databricks-sql-connector >=4.0.4
  run_constrained:
    - databricks-sdk >=0.40.0

test:
  imports:
    - harlequin_databricks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alexmalins/harlequin-databricks
  summary: A Harlequin adapter for Databricks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
    - alexmalins
